[project]
name = "sandbox-server"
version = "0.1.0"
description = "MCP sandbox server for running code in containers"
dependencies = [
    "mcp>=1.2.0",
    "docker>=6.1.0",
    "requests>=2.25.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"